/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: ['deen3evddmddt.cloudfront.net'],
  },
  env: {
    VERSION: '3.0.46',
    APP_NAME: 'WsCube Tech',
    NEXT_PUBLIC_SITE_URL: 'https://www.wscubetech.com',

    LANDING_IMG_PATH: '/',
    IMG_PATH: 'https://deen3evddmddt.cloudfront.net/', // staging
    LOCAL_IMAGE_PATH: '/',
    APPLICATION_IMG_PATH: "https://d3gawjs9lfpyh2.cloudfront.net/",
    // APPLICATION_IMG_PATH: "https://d2nuw0239dzqdp.cloudfront.net/", //staging

    // local urls
    // DASHBOARD_URL: 'https://dev.wscubetech.com/lms',
    // API_BASE_URL: 'https://dev.wscubetech.com/services/webapi/',
    // // COOKIES_DOMAIN: 'localhost',
    // COOKIES_DOMAIN: 'dev.wscubetech.com',
    // LEAD_API_BASE_URL: 'https://devapi.digitaltyari.com/crm-backend/public/services-api/',

    // production urls
    DASHBOARD_URL: 'https://lms.wscubetech.com',
    API_BASE_URL: 'https://ws-api.wscubetech.com/webapi/',
    COOKIES_DOMAIN: '.wscubetech.com',
    LEAD_API_BASE_URL: 'https://crm.wscubetech.com/services-api/',

    LOG_IN: 'auth/login',
    SIGN_UP: 'auth/register',
    VERIFY_OTP: 'auth/verify-otp',
    RESEND_OTP: 'auth/resend-otp',
    FORGOT_PASSWORD: 'auth/forgot-password',
    RESET_PASSWORD: 'auth/set-password',
    CHECK_RESET_URL: 'auth/check-reset-url',
    USER_PROFILE: 'auth/user-profile',

    GET_CATEGORY_LIST: 'categories',
    GET_ALL_COURSE_LIST: 'courses/all-list',
    GET_COURSE_LIST: 'courses/home-list',
    GET_CENTERS_LIST: 'others/centers-list',
    GET_COURSE_DETAILS: 'courses/details',
    GET_COURSE_FEATURES: 'courses/features',
    GET_COURSE_HIGHLIGHTS: 'courses/highlights',
    GET_COURSE_TOOLS: 'courses/tools',
    GET_COURSE_CURRICULUM: 'courses/curriculums',
    GET_COURSE_FEE: 'courses/fee-structure',
    GET_COURSE_MENTORS: 'courses/mentors',
    GET_COURSE_TESTIMONIALS: 'courses/testimonials',
    GET_COURSE_FAQS: 'courses/faqs',
    GET_COURSE_COHORTS: 'courses/cohorts',
    GET_IN_TOUCH: 'others/contact-us',
    GET_MASTER_CLASS_LIST: 'master-class/list',
    GET_MASTER_CLASS_CATEGORY_LIST: 'master-class/categories',
    GET_MASTERCLASS_DETAILS: 'master-class/details',
    GET_MASTERCLASS_FEATURES: 'master-class/features',
    GET_TESTMONIALS_LIST: 'others/testimonials',
    GET_MENTOR_DETAILS: 'others/mentor-details',
    // Lead generate
    // GET_LEAD_COURSE_LIST: 'get-courses',
    // GET_EDUCATION: 'get-educations',
    // LEAD_STORE: 'store-leads',
    // LEAD_RESEND_OTP: 'resend-lead-mobile-opt',
    // LEAD_VERIFY_OTP: 'lead-mobile-verify',
    // WS_LEAD_STORE: 'services/store-leads',
    GET_LEAD_COURSE_LIST: 'services/get-courses',
    GET_EDUCATION: 'services/get-educations',
    LEAD_STORE: 'services/store-leads',
    LEAD_RESEND_OTP: 'services/resend-lead-mobile-otp',
    LEAD_VERIFY_OTP: 'services/lead-mobile-verify',
    // WS_LEAD_STORE: 'services/store-leads',


    GET_HOME_DETAILS: 'categories/home-details',
    TOP_RECRUITERS_LIST: 'categories/top-recruiters',
    GET_IMPACTFUL_NUMBERS_LIST: 'others/impactful-numbers',
    GET_CATEGORY_COURSES_LIST: 'categories/courses',
    GET_MENTORSHIP_COURSES_LIST: 'categories/mentorship-program',


    HOME_MENTORS_LIST: 'others/mentors-list',
    GET_CATEGORY_MENTORS_LIST: 'categories/mentors',
    GET_CATEGORY_DETALS: 'categories/details',

    GET_CATEGORY_JOB_OPENINGS: 'categories/job-openings',
    GET_CATEGORY_TARGET_ROLES: 'categories/job-target-roles',
    GET_META_DETAILS: 'others/meta-details',
    GET_ONLINE_XML_COURSE_LIST: 'courses/online-xml',
    GET_OFFLINE_XML_COURSE_LIST: 'others/get-center-with-course',
    GET_CATEGORY_TESTMONIALS: 'categories/testimonials',
    GET_CRM_COURSE_NAME: 'courses/crm-course',
    GET_TOPBAR_CONTENT: 'others/top-bar-cotent',

    // Master class 
    // REGISTER_MASTER_EVENT: 'event-enrollment/v2',
    REGISTER_MASTER_EVENT: 'services/enroll-master-class',
    GET_EVENT_SHORT_DETAILS: 'master-class/min-details',

    // Apply now form
    GET_COURSE_QUESTIONS: 'get-course-question',
    GET_COURSE_SUB_QUESTIONS: 'get-course-sub-question',
    SUBMIT_CRS_QUESTION: 'submit-course-question',
    GET_TOP_COMPANIES: 'others/top-companies',
    GET_CENTER_ALUMNIS: 'others/get-center-alumnis',
    GET_CENTER_DETAILS: 'others/get-center-details',
    GET_CENTER_FAQ: 'others/get-center-faq',
    UPLOAD_LEAD_USER_PROFILE: 'upload-lead-user-image',
    // COUNTRY_LIST: 'get-countries',
    COUNTRY_LIST: 'services/get-countries',
    PORTFOLIO_LIST: 'portfolio/list',
    PORTFOLIO_CATEGORY_DETAILS: 'portfolio/category-details',
    PORTFOLIO_DETAILS: 'portfolio/get-portfolio-details',
    GET_PROJECTS_LIST: 'portfolio/get-projects',
    GET_AWARDS_LIST: 'portfolio/get-awards',
    GET_TECHNICIAL_SKILLS: 'others/get-technical-skills',
    PORTFOLIO_CATEGORY_LIST: 'portfolio/category-list',
    PORTFOLIO_PROJECTS: 'portfolio/get-project-list',
    PORTFOLIO_AWARDS: 'portfolio/get-award-list',

    // faq
    FAQ_BASIC_INFO: 'faqs/details',
    GET_FAQ_LIST: 'faqs/get-faq-list',
    GET_COURSE_QUESTION: 'services/get-course-question',
    GET_COURSE_SUB_QUESTION: 'services/get-course-sub-question',
    SUBMIT_COURSE_QUESTION: 'services/submit-course-question',
    UPLOAD_DOCUMENTS: 'services/upload',
    GET_APPLICATION_COURSE: 'courses/crm-course',

    // DA lead api
    // DA_LEAD_STORE: 'lead-otp',
    // DA_LEAD_VERIFY_OTP: 'lead-otp-verify',
    // DA_LEAD_RESEND_OTP: 'resend-lead-otp',
    DA_LEAD_STORE: 'services/lead-otp',
    DA_LEAD_VERIFY_OTP: 'services/lead-otp-verify',
    DA_LEAD_RESEND_OTP: 'services/resend-lead-otp',

    // sitemap
    GET_RESOURCES_SITEMAP: 'resources/get-site-map',
    GET_FREE_COURSES_LIST: 'free-courses/list',
    GET_STICKY_ADS_CONTENT: 'others/get-banner-details',

    // Portfolio for Admin
    PORTFOLIO_DETAILS_FOR_ADMIN: 'portfolio/admin-portfolio-details',
  },
  async redirects() {
    return [
      {
        source: '/full-stack-development-course-jodhpur.html',
        destination: '/jodhpur/full-stack-developer-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/wordpress-training-course-jodhpur.html',
        destination: '/jodhpur/wordpress-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/web-development-training-certification-course-jodhpur.html',
        destination: '/jodhpur/web-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/mern-stack-training-jodhpur.html',
        destination: '/jodhpur/mern-stack-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/php-training-certification-course-jodhpur.html',
        destination: '/jodhpur/php-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/javascript-training-certification-course-jodhpur.html',
        destination: '/jodhpur/javascript-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/bootstrap-training-certification-course-jodhpur.html',
        destination: '/jodhpur/bootstrap-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/laravel-training-jodhpur.html',
        destination: '/jodhpur/laravel-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/nodejs-development-training-certification-jodhpur.html',
        destination: '/jodhpur/nodejs-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/angularjs-development-training-certification-jodhpur.html',
        destination: '/jodhpur/angularjs-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/reactjs-training-course-jodhpur.html',
        destination: '/jodhpur/reactjs-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/python-training-jodhpur.html',
        destination: '/jodhpur/python-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/java-j2se-training-certification-course-jodhpur.html',
        destination: '/jodhpur/java-j2se-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/c-programming-development-training-certification-jodhpur.html',
        destination: '/jodhpur/c-programming-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/cpp-programming-development-training-certification-jodhpur.html',
        destination: '/jodhpur/cpp-programming-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/seo-training-course-jodhpur.html',
        destination: '/jodhpur/seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-jodhpur.html',
        destination: '/jodhpur/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/content-writing-course-jodhpur.html',
        destination: '/jodhpur/content-writing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/google-ads-training-course-jodhpur.html',
        destination: '/jodhpur/google-ads-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/android-development-training-jodhpur.html',
        destination: '/jodhpur/android-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/flutter-training-course-jodhpur.html',
        destination: '/jodhpur/flutter-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/data-science-training-course-jodhpur.html',
        destination: '/jodhpur/data-science-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/data-analytics-course-jodhpur.html',
        destination: '/jodhpur/data-analytics-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/graphic-designing-course-jodhpur.html',
        destination: '/jodhpur/graphic-designing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/ethical-hacking-course-jodhpur.html',
        destination: '/jodhpur/ethical-hacking-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/penetration-testing-course-jodhpur.html',
        destination: '/jodhpur/penetration-testing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/web-development-course-jaipur.html',
        destination: '/jaipur/web-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/web-designing-course-jaipur.html',
        destination: '/jaipur/web-designing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/mern-stack-development-course-jaipur.html',
        destination: '/jaipur/mern-stack-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/laravel-training-jaipur.html',
        destination: '/jaipur/laravel-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/reactjs-training-jaipur.html',
        destination: '/jaipur/reactjs-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/php-training-jaipur.html',
        destination: '/jaipur/php-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/angularjs-training-jaipur.html',
        destination: '/jaipur/angularjs-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/nodejs-training-jaipur.html',
        destination: '/jaipur/nodejs-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/javascript-training-jaipur.html',
        destination: '/jaipur/javascript-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/html-training-jaipur.html',
        destination: '/jaipur/html-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/wordpress-training-course-jaipur.html',
        destination: '/jaipur/wordpress-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/java-training-jaipur.html',
        destination: '/jaipur/java-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/c-language-course-jaipur.html',
        destination: '/jaipur/c-language-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/cpp-course-jaipur.html',
        destination: '/jaipur/cpp-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/seo-course-jaipur.html',
        destination: '/jaipur/seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-jaipur.html',
        destination: '/jaipur/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/social-media-marketing-course-jaipur.html',
        destination: '/jaipur/social-media-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/google-ads-training-course-jaipur.html',
        destination: '/jaipur/google-ads-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/data-analytics-course-jaipur.html',
        destination: '/jaipur/data-analytics-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/graphic-designing-course-jaipur.html',
        destination: '/jaipur/graphic-designing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/penetration-testing-course-jaipur.html',
        destination: '/jaipur/penetration-testing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/training-courses.html',
        destination: '/',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/online-web-development-course-india.html',
        destination: '/web-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/full-stack-developer-course.html',
        destination: '/full-stack-developer-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/best-wordpress-online-course-india.html',
        destination: '/wordpress-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-mern-stack-developer-course-india.html',
        destination: '/mern-stack-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-html-course.html',
        destination: '/html-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/reactjs-course.html',
        destination: '/reactjs-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/javascript-course.html',
        destination: '/javascript-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/php-course.html',
        destination: '/php-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-power-bi-course.html',
        destination: '/power-bi-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/tableau-course.html',
        destination: '/tableau-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/nodejs-course.html',
        destination: '/nodejs-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/front-end-development-course.html',
        destination: '/front-end-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/web-designing-course.html',
        destination: '/web-designing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/css-course.html',
        destination: '/css-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/laravel-course.html',
        destination: '/laravel-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-android-app-development-course-india.html',
        destination: '/android-app-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/flutter-online-course-india.html',
        destination: '/flutter-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/mobile-app-development-course.html',
        destination: '/mobile-app-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-seo-course-india.html',
        destination: '/seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-digital-marketing-course-india.html',
        destination: '/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-content-writing-course.html',
        destination: '/content-writing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-advertising-course-india.html',
        destination: '/performance-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-youtube-seo-marketing-course-india.html',
        destination: '/youtube-seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/social-media-marketing-course.html',
        destination: '/social-media-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/google-ads-course.html',
        destination: '/google-ads-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/copywriting-course.html',
        destination: '/copywriting-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/instagram-marketing-course.html',
        destination: '/instagram-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-data-science-certification-course.html',
        destination: '/data-science-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-python-certification-course-india.html',
        destination: '/python-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-data-analytics-course.html',
        destination: '/data-analytics-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/graphic-design-course.html',
        destination: '/graphic-designing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-ethical-hacking-course.html',
        destination: '/ethical-hacking-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-pentesting-course.html',
        destination: '/penetration-testing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/cyber-security-course.html',
        destination: '/cyber-security-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-kota-rajasthan.html',
        destination: '/kota/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/seo-course-kota.html',
        destination: '/kota/seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/python-programming-course-kota.html',
        destination: '/kota/python-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/web-development-course-kota.html',
        destination: '/kota/web-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-sikar.html',
        destination: '/sikar/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/seo-course-sikar.html',
        destination: '/sikar/seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/web-development-course-sikar.html',
        destination: '/sikar/web-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-ajmer.html',
        destination: '/ajmer/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/seo-course-ajmer.html',
        destination: '/ajmer/seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-bhilwara.html',
        destination: '/bhilwara/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/seo-training-course-bhilwara.html',
        destination: '/bhilwara/seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-training-course-bikaner.html',
        destination: '/bikaner/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/web-development-course-bikaner.html',
        destination: '/bikaner/web-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-training-pali.html',
        destination: '/pali/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-noida.html',
        destination: '/noida/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/python-training-course-noida.html',
        destination: '/noida/python-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/full-stack-web-development-course-noida.html',
        destination: '/noida//full-stack-developer-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/content-writing-course-noida.html',
        destination: '/noida/content-writing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-sri-ganganagar.html',
        destination: '/sri-ganganagar/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-alwar.html',
        destination: '/alwar/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-barmer.html',
        destination: '/bikaner/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-jaisalmer.html',
        destination: '/jaisalmer/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-lucknow.html',
        destination: '/lucknow/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/content-writing-course-lucknow.html',
        destination: '/lucknow/content-writing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-kanpur.html',
        destination: '/kanpur/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/full-stack-web-development-course-kanpur.html',
        destination: '/kanpur/full-stack-developer-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-ghaziabad.html',
        destination: '/ghaziabad/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-udaipur.html',
        destination: '/udaipur/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/seo-course-udaipur.html',
        destination: '/udaipur/seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/python-training-course-udaipur.html',
        destination: '/udaipur/python-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/web-development-course-udaipur.html',
        destination: '/udaipur/web-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/content-writing-course-udaipur.html',
        destination: '/udaipur/content-writing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-agra.html',
        destination: '/agra/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/full-stack-web-development-course-agra.html',
        destination: '/agra/full-stack-developer-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-patna.html',
        destination: '/patna/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-meerut.html',
        destination: '/meerut/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-bareilly.html',
        destination: '/bareilly/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-varanasi.html',
        destination: '/varanasi/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-indore.html',
        destination: '/indore/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/seo-course-indore.html',
        destination: '/indore/seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/python-training-course-indore.html',
        destination: '/indore/python-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/web-development-course-indore.html',
        destination: '/indore/web-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/content-writing-course-indore.html',
        destination: '/indore/content-writing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/data-science-course-indore.html',
        destination: '/indore/data-science-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/android-development-training-indore.html',
        destination: '/indore/android-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/flutter-training-course-indore.html',
        destination: '/indore/flutter-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/mern-stack-course-indore.html',
        destination: '/indore/mern-stack-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/ethical-hacking-course-indore.html',
        destination: '/indore/ethical-hacking-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-bhopal.html',
        destination: '/bhopal/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/seo-training-course-bhopal.html',
        destination: '/bhopal/seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/python-training-course-bhopal.html',
        destination: '/bhopal/python-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/web-development-course-bhopal.html',
        destination: '/bhopal/web-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/mern-stack-training-course-bhopal.html',
        destination: '/bhopal/mern-stack-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/digital-marketing-course-pune.html',
        destination: '/pune/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/seo-training-course-pune.html',
        destination: '/pune/seo-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/python-training-course-pune.html',
        destination: '/pune/python-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/web-development-course-pune.html',
        destination: '/pune/web-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/content-writing-course-pune.html',
        destination: '/pune/content-writing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/best-digital-marketing-course-delhi.html',
        destination: '/delhi/digital-marketing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/content-writing-course-delhi.html',
        destination: '/delhi/content-writing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/python-training-course-jaipur.html',
        destination: '/jaipur/python-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/content-writing-course-jaipur.html',
        destination: '/jaipur/content-writing-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/data-science-course-jaipur.html',
        destination: '/jaipur/data-science-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/android-app-development-course-jaipur.html',
        destination: '/jaipur/android-app-development-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/flutter-development-course-jaipur.html',
        destination: '/jaipur/flutter-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/ethical-hacking-course-jaipur.html',
        destination: '/jaipur/ethical-hacking-course',
        permanent: true,
        statusCode: 301,
      },
      // Internship Page
      {
        source: '/bca-internship-jodhpur.html',
        destination: '/blog/bca-internship-jodhpur',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/mca-internship-training-institute-jodhpur.html',
        destination: '/blog/mca-internship-jodhpur',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/bsc-it-internship-training-institute-jodhpur.html',
        destination: '/blog/bsc-it-internship-jodhpur',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/msc-it-internship-training-institute-jodhpur.html',
        destination: '/blog/msc-it-internship-jodhpur',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/btech-internship-jodhpur.html',
        destination: '/blog/btech-internship-jodhpur',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/polytechnic-internship-training-institute-jodhpur.html',
        destination: '/blog/polytechnic-internship-jodhpur',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/internship-summer-training-jodhpur.html',
        destination: '/blog/internship-summer-training-jodhpur',
        permanent: true,
        statusCode: 302,
      },
      // Resources Free Courses Pages
      {
        source: '/online-semrush-course.html',
        destination: '/resources/semrush/free-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-google-tag-manager-course.html',
        destination: '/resources/google-tag-manager/free-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-blogging-course.html',
        destination: '/resources/blogging/free-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-affiliate-marketing-course.html',
        destination: '/resources/affiliate-marketing/free-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-photoshop-course.html',
        destination: '/resources/photoshop/free-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-video-editing-course.html',
        destination: '/resources/video-editing/free-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-angular-course.html',
        destination: '/resources/angular/free-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-shopify-course.html',
        destination: '/resources/shopify/free-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/online-django-course.html',
        destination: '/resources/django/free-course',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/email-marketing-course.html',
        destination: '/resources/email-marketing/free-course',
        permanent: true,
        statusCode: 301,
      },
      // CMS Pages
      {
        source: '/about-us.html',
        destination: '/about',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/contact-us.html',
        destination: '/contact',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/privacy-policy.html',
        destination: '/privacy-policy',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/terms-and-conditions.html',
        destination: '/terms-and-conditions',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/refund-and-cancellation.html',
        destination: '/refund-and-cancellation',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/student-testimonials.html',
        destination: '/',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/careers.html',
        destination: '/',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/become-instructor.html',
        destination: '/',
        permanent: true,
        statusCode: 302,
      },
      // Quiz
      {
        source: '/quiz-test-html.html',
        destination: '/resources/html/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/quiz-test-php.html',
        destination: '/resources/php/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/quiz-test-css.html',
        destination: '/resources/css/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/quiz-test-javascript.html',
        destination: '/resources/javascript/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/quiz-test-mysql.html',
        destination: '/resources/mysql/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/quiz-test-c.html',
        destination: '/resources/c-programming/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/reactjs-mcq-quiz.html',
        destination: '/resources/reactjs/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/ethical-hacking-mcq-quiz.html',
        destination: '/resources/ethical-hacking/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/java-mcq-quiz.html',
        destination: '/resources/java/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/data-science-mcq-quiz.html',
        destination: '/resources/data-science/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/quiz-test-seo.html',
        destination: '/resources/seo/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/quiz-test-html5.html',
        destination: '/resources/html5/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/quiz-test-css3.html',
        destination: '/resources/css3/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/quiz-test-android.html',
        destination: '/resources/android/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/quiz-test-jquery.html',
        destination: '/resources/jquery/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/quiz-test-cpp.html',
        destination: '/resources/cpp/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/machine-learning-mcq-quiz.html',
        destination: '/resources/machine-learning/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/python-mcq-quiz.html',
        destination: '/resources/python/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/cyber-security-mcq-quiz.html',
        destination: '/resources/cyber-security/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/sql-mcq-quiz.html',
        destination: '/resources/sql/quiz',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/jodhpur-center.html',
        destination: '/jodhpur',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/jaipur-center.html',
        destination: '/jaipur',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/sitemap.html',
        destination: '/',
        permanent: true,
        statusCode: 302,
      },
      {
        source: '/events.html',
        destination: '/events',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/dashboard',
        destination: 'https://lms.wscubetech.com',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/web-development-training-certification-course-jodhpur.html',
        destination: 'http://live.wscubetech.com/landing-pages/web-development-training-certification-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/wordpress-training-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/wordpress-training-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/laravel-training-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/laravel-training-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/javascript-training-certification-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/javascript-training-certification-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/reactjs-training-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/reactjs-training-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/python-training-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/python-training-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/seo-training-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/seo-training-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/content-writing-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/content-writing-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/android-development-training-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/android-development-training-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/flutter-training-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/flutter-training-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/data-science-training-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/data-science-training-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/graphic-designing-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/graphic-designing-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/ethical-hacking-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/ethical-hacking-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/penetration-testing-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/penetration-testing-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-web-development-course-india.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-web-development-course-india.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/best-wordpress-online-course-india.html',
        destination: 'https://live.wscubetech.com/landing-pages/best-wordpress-online-course-india.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-data-science-certification-course.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-data-science-certification-course.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-android-app-development-course-india.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-android-app-development-course-india.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/flutter-online-course-india.html',
        destination: 'https://live.wscubetech.com/landing-pages/flutter-online-course-india.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-ethical-hacking-course.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-ethical-hacking-course.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-pentesting-course.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-pentesting-course.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-python-certification-course-india.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-python-certification-course-india.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-seo-course-india.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-seo-course-india.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-digital-marketing-course-india.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-digital-marketing-course-india.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-content-writing-course.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-content-writing-course.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/bootstrap-training-certification-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/bootstrap-training-certification-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/java-j2se-training-certification-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/java-j2se-training-certification-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/nodejs-development-training-certification-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/nodejs-development-training-certification-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/php-training-certification-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/php-training-certification-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/angularjs-development-training-certification-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/angularjs-development-training-certification-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-advertising-course-india.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-advertising-course-india.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-youtube-seo-marketing-course-india.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-youtube-seo-marketing-course-india.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-mern-stack-developer-course-india.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-mern-stack-developer-course-india.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/cpp-programming-development-training-certification-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/cpp-programming-development-training-certification-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-kota-rajasthan.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-kota-rajasthan.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-sikar.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-sikar.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-ajmer.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-ajmer.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-bhilwara.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-bhilwara.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-training-course-bikaner.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-training-course-bikaner.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-training-pali.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-training-pali.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-noida.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-noida.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-sri-ganganagar.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-sri-ganganagar.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-alwar.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-alwar.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-barmer.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-barmer.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-jaisalmer.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-jaisalmer.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/seo-course-ajmer.html',
        destination: 'https://live.wscubetech.com/landing-pages/seo-course-ajmer.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/seo-course-sikar.html',
        destination: 'https://live.wscubetech.com/landing-pages/seo-course-sikar.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/web-development-course-kota.html',
        destination: 'https://live.wscubetech.com/landing-pages/web-development-course-kota.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-kanpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-kanpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-ghaziabad.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-ghaziabad.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/full-stack-web-development-course-agra.html',
        destination: 'https://live.wscubetech.com/landing-pages/full-stack-web-development-course-agra.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-udaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-udaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-agra.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-agra.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-patna.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-patna.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/python-training-course-noida.html',
        destination: 'https://live.wscubetech.com/landing-pages/python-training-course-noida.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/seo-course-udaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/seo-course-udaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/seo-course-kota.html',
        destination: 'https://live.wscubetech.com/landing-pages/seo-course-kota.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/seo-training-course-bhilwara.html',
        destination: 'https://live.wscubetech.com/landing-pages/seo-training-course-bhilwara.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-meerut.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-meerut.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/full-stack-web-development-course-noida.html',
        destination: 'https://live.wscubetech.com/landing-pages/full-stack-web-development-course-noida.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-bareilly.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-bareilly.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/content-writing-course-noida.html',
        destination: 'https://live.wscubetech.com/landing-pages/content-writing-course-noida.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/web-development-course-sikar.html',
        destination: 'https://live.wscubetech.com/landing-pages/web-development-course-sikar.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-varanasi.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-varanasi.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-indore.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-indore.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-bhopal.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-bhopal.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/seo-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/seo-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/python-training-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/python-training-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/content-writing-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/content-writing-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/web-development-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/web-development-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/web-development-course-pune.html',
        destination: 'https://live.wscubetech.com/landing-pages/web-development-course-pune.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/data-science-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/data-science-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/python-training-course-pune.html',
        destination: 'https://live.wscubetech.com/landing-pages/python-training-course-pune.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/android-app-development-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/android-app-development-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/seo-training-course-pune.html',
        destination: 'https://live.wscubetech.com/landing-pages/seo-training-course-pune.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-pune.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-pune.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/content-writing-course-lucknow.html',
        destination: 'https://live.wscubetech.com/landing-pages/content-writing-course-lucknow.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/content-writing-course-delhi.html',
        destination: 'https://live.wscubetech.com/landing-pages/content-writing-course-delhi.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/web-development-course-bhopal.html',
        destination: 'https://live.wscubetech.com/landing-pages/web-development-course-bhopal.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/flutter-development-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/flutter-development-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/mern-stack-development-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/mern-stack-development-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/ethical-hacking-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/ethical-hacking-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/c-programming-development-training-certification-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/c-programming-development-training-certification-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/web-development-course-udaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/web-development-course-udaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/python-programming-course-kota.html',
        destination: 'https://live.wscubetech.com/landing-pages/python-programming-course-kota.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/python-training-course-udaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/python-training-course-udaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/digital-marketing-course-lucknow.html',
        destination: 'https://live.wscubetech.com/landing-pages/digital-marketing-course-lucknow.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/full-stack-web-development-course-kanpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/full-stack-web-development-course-kanpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-data-analytics-course.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-data-analytics-course.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/content-writing-course-udaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/content-writing-course-udaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/web-development-course-bikaner.html',
        destination: 'https://live.wscubetech.com/landing-pages/web-development-course-bikaner.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/online-youtube-seo-marketing-course-india-ads.html',
        destination: 'https://live.wscubetech.com/landing-pages/online-youtube-seo-marketing-course-india-ads.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/wordpress-training-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/wordpress-training-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/data-analytics-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/data-analytics-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/graphic-designing-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/graphic-designing-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/web-designing-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/web-designing-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/laravel-training-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/laravel-training-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/reactjs-training-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/reactjs-training-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/php-training-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/php-training-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/angularjs-training-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/angularjs-training-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/nodejs-training-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/nodejs-training-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/javascript-training-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/javascript-training-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/html-training-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/html-training-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/social-media-marketing-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/social-media-marketing-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/google-ads-training-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/google-ads-training-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/penetration-testing-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/penetration-testing-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/cpp-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/cpp-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/c-language-course-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/c-language-course-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/java-training-jaipur.html',
        destination: 'https://live.wscubetech.com/landing-pages/java-training-jaipur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/data-analytics-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/data-analytics-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/full-stack-development-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/full-stack-development-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/python-training-course-bhopal.html',
        destination: 'https://live.wscubetech.com/landing-pages/python-training-course-bhopal.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/mern-stack-training-course-bhopal.html',
        destination: 'https://live.wscubetech.com/landing-pages/mern-stack-training-course-bhopal.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/seo-training-course-bhopal.html',
        destination: 'https://live.wscubetech.com/landing-pages/seo-training-course-bhopal.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/google-ads-training-course-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/google-ads-training-course-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/mern-stack-training-jodhpur.html',
        destination: 'https://live.wscubetech.com/landing-pages/mern-stack-training-jodhpur.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/full-stack-developer-course.html',
        destination: 'https://live.wscubetech.com/landing-pages/full-stack-developer-course.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/graphic-design-course.html',
        destination: 'https://live.wscubetech.com/landing-pages/graphic-design-course.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/verify-certificate.html',
        destination: 'https://live.wscubetech.com/verify-certificate.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/verify-certificate',
        destination: 'https://live.wscubetech.com/verify-certificate.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/verify-counsellor.html',
        destination: 'https://live.wscubetech.com/verify-counsellor.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/event-certificate.html',
        destination: 'https://live.wscubetech.com/event-certificate.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/event-review.html',
        destination: 'https://live.wscubetech.com/event-review.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/data-analytics-masterclass.html',
        destination: 'https://live.wscubetech.com/landing-pages/data-analytics-masterclass.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/landing-pages/uber-data-analytics-masterclass.html',
        destination: 'https://live.wscubetech.com/landing-pages/uber-data-analytics-masterclass.html',
        permanent: true,
        statusCode: 301,
      },
      {
        source: '/index.html',
        destination: '/',
        permanent: true,
        statusCode: 301,
      },
    ];
  },
};

export default nextConfig;
